# -*- coding: utf-8 -*-
"""
Validate that the features calculations in movement_validation
match those of the original Matlab codebase, by comparing
calculated features with a saved copy of the file generated by 
the original Matlab code.

To run this code files should be obtained from:
https://drive.google.com/folderview?id=0B7to9gBdZEyGNWtWUElWVzVxc0E&usp=sharing

In addition the user_config.py file should be created in the 
movement_validation package based on the user_config_example.txt

"""
import sys, os, warnings
import numpy as np

# We must add .. to the path so that we can perform the 
# import of movement_validation while running this as 
# a top-level script (i.e. with __name__ = '__main__')
sys.path.append('..')
import movement_validation as mv


def test_features():
    warnings.filterwarnings('error')
    
    """
    Compare Schafer-generated features with our new code's generated features

    """
    # Set up the necessary file paths for file loading
    #----------------------
    base_path = os.path.abspath(mv.user_config.EXAMPLE_DATA_PATH)
    matlab_generated_file_path = os.path.join(
        base_path,'example_video_feature_file.mat')
    data_file_path = os.path.join(base_path,"example_video_norm_worm.mat")

    # OPENWORM
    #----------------------
    # Load the normalized worm from file
    nw = mv.NormalizedWorm.from_schafer_file_factory(data_file_path)

    # Generate the OpenWorm movement validation repo version of the features
    openworm_features = mv.WormFeatures(nw)

    # SCHAFER LAB
    #----------------------
    # Load the Matlab codes generated features from disk
    matlab_worm_features = \
        mv.WormFeatures.from_disk(matlab_generated_file_path)
        
    
    df = openworm_features.get_DataFrame()
    
    def length(x):
        if x is None:
            return np.NaN
        try:
            return len(x)
        except TypeError:
            # e.g. len(5) will raise TypeError
            if isinstance(x, (int, float, complex)):
                return 1
            else:
                return np.NaN

    df['length'] = df['data_array'].map(length)
    
    # TODO: add a column for feature_field
    # TODO: pivot so the rows are the frames and the columns are the features
    #      NOTE: This only works for movement features.
    # TODO: add this as a method of worm_features
    # TODO: add metadata to the feature specifications noting what length
    #       the data should have.  Figure out if there are errors.

    import pdb
    pdb.set_trace()


    # COMPARISON
    #----------------------
    # Show the results of the comparison
    print("\nComparison of computed features to those computed with "
          "old Matlab code:")

    categories = ['locomotion', 'posture', 'morphology', 'path']
    
    # Compare each feature category to make sure they are equal
    for category in categories:
        is_test_passed = (getattr(matlab_worm_features, category) ==
                          getattr(openworm_features, category))
        print(str.capitalize(category)+ ": " + str(is_test_passed))
        assert(is_test_passed)

    print("\nDone validating features")


if __name__ == '__main__':
    start_time = mv.utils.timing_function()
    test_features()
    print("Time elapsed: %.2f seconds" % 
          (mv.utils.timing_function() - start_time))
    
